### ISSUE TITLE
Lidar and radar timestamps with the same name cannot correspond

### ISSUE THREAD

**Issue by liuzhaoo** [akarsh-prabhakara/RadarHD#2]
Thank you for the new data.

But when I running the `create_dataset_all_radar_lidar.py` script,I found that the timestamps of the same set of data cannot be matched.

Furthermore, when processing radar data, the function `get_global_timestamps` cannot return the correct timestamp

Below are relevant screenshots，is this normal?

<img width="964" alt="image" src="https://github.com/akarsh-prabhakara/RadarHD/assets/50330745/1cf17cf2-dbef-4744-980a-8b3b960de3fd">

**Comment by akarsh-prabhakara** [comment]
This is a timezone issue. Because of python datetime package giving results in local time as opposed to UTC or ET (which was assumed when writing this code). A short term fix is to set your location as US/Eastern when prompted during `sh install.sh`. The radar and lidar timestamps should then match. Here is what it should look like.

![image](https://github.com/akarsh-prabhakara/RadarHD/assets/13760516/8a2ea339-25ae-4d30-bcc4-db174668440e)

**Comment by liuzhaoo** [comment]
I fixed the issue by directly changing the system timezone to US Eastern

**Comment by akarsh-prabhakara** [comment]
Sure, that works too.
